# Generated by Django 3.0.5 on 2020-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank=True, upload_to='blog/post_pictures'),
        ),
    ]
