# Generated by Django 3.0.5 on 2020-06-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='blog.Blog'),
        ),
    ]
