# Generated by Django 3.0.5 on 2020-06-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_make_decision', 'Can approve or deny comments'),)},
        ),
    ]
